import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface AboutText {
	introduceTitle: string
	introduceDescription: string
	specialityTitle: string
	specialityDescription: string
	collaborateTitle: string
	collaborateDescription: string
}

let TextData = {
	en: {
		"introduceTitle": "Who We are?",
		"introduceDescription": "We are a team of thinkers, engineers, designers, and marketers who represent different cultures around the globe, working together to build better solutions for future world.",
		"specialityTitle": "We use Modern Tools & Technologies.",
		"specialityDescription": "Hence technologies are updating day by day, We always try to keep up with the latest technologies & tools to make our products better, reliable, faster, and secure. By doing so we can provide the best solutions and products for our valued customers as they wish. Here are some of the latest technologies & tools we use to build our products recognized by professionals in the industry:",
		"collaborateTitle": "Let's Collaborate With Us.",
		"collaborateDescription": "We are passionate to build new digital products for a better future by collaborating with new clients. If you have an idea to create a new digital product for your business needs or any other questions, inquire us. Our team/specialists are always available to help you."
	} as AboutText,
}

export default function (): AboutText {
    return TextData[lang];
}