import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface ContactText {
	contactUs: string
	contactUsDescription: string
	liveChatTitle: string
	liveChatDes: string
	liveChatBtn: string
	emailUsTitle: string
	emailUsDes: string
	emailUsBtn: string
}

let TextData = {
	en: {
		"contactUs": "Contact Us",
		"contactUsDescription": "We work alongside our customers. When we start a project, you become a member of our bitzquad family. You have all the freedom to discuss and clarify every aspect of 'our' project.",
		"liveChatTitle": "Live Chat",
		"liveChatDes": "Live chat directly from this website",
		"liveChatBtn": "Live Chat",
		"emailUsTitle": "Email Us",
		"emailUsDes": "Send us a mail from your official email",
		"emailUsBtn": "Email Us"
	} as ContactText,
}

export default function (): ContactText {
    return TextData[lang];
}