import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface ContactFormText {
	title: string
	description: string
	placeholderName: string
	placeholderEmail: string
	placeholderSubject: string
	placeholderMessage: string
	submitBtn: string
}

let TextData = {
	en: {
		"title": "Let's talk",
		"description": "We will reply soon",
		"placeholderName": "Name",
		"placeholderEmail": "Email",
		"placeholderSubject": "Subject",
		"placeholderMessage": "Your Message",
		"submitBtn": "Send Message"
	} as ContactFormText,
	si: {
		"title": "එන්න, අපි ඔබේ ව්‍යාපාරය ගැන කතා කරමු",
		"description": "",
		"placeholderName": "නම",
		"placeholderEmail": "විද්‍යුත් තැපැල් ලිපිනය",
		"placeholderSubject": "විෂය/මාතෘකාව",
		"placeholderMessage": "ඔබගේ පණිවිඩය",
		"submitBtn": "පණිවිඩ යවන්න"
	} as ContactFormText,
	it: {
		"title": "Parliamo",
		"description": "",
		"placeholderName": "Nome",
		"placeholderEmail": "Email",
		"placeholderSubject": "Oggetto",
		"placeholderMessage": "Il tuo messaggio",
		"submitBtn": "Invia messaggio"
	} as ContactFormText,
	ja: {
		"title": "",
		"description": "",
		"placeholderName": "",
		"placeholderEmail": "",
		"placeholderSubject": "",
		"placeholderMessage": "",
		"submitBtn": ""
	} as ContactFormText,
	zh: {
		"title": "",
		"description": "",
		"placeholderName": "",
		"placeholderEmail": "",
		"placeholderSubject": "",
		"placeholderMessage": "",
		"submitBtn": ""
	} as ContactFormText,
	ta: {
		"title": "",
		"description": "",
		"placeholderName": "",
		"placeholderEmail": "",
		"placeholderSubject": "",
		"placeholderMessage": "",
		"submitBtn": ""
	} as ContactFormText,
}

export default function (): ContactFormText {
    return TextData[lang];
}