import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface ContactFormText {
	title: string
	description: string
	placeholderName: string
	placeholderEmail: string
	placeholderSubject: string
	placeholderMessage: string
	submitBtn: string
}

let TextData = {
	en: {
		"title": "Let's talk",
		"description": "We will reply soon",
		"placeholderName": "Name",
		"placeholderEmail": "Email",
		"placeholderSubject": "Subject",
		"placeholderMessage": "Your Message",
		"submitBtn": "Send Message"
	} as ContactFormText,
}

export default function (): ContactFormText {
    return TextData[lang];
}