import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface ErrorText {
	msg404: string
	decription404: string
	msgUnknown: string
	decriptionUnknown: string
}

let TextData = {
	en: {
		"msg404": "404 not found",
		"decription404": "The page you are looking for does not exist.",
		"msgUnknown": "Something went wrong",
		"decriptionUnknown": "Please try again in a different way. If the problem persists, contact customer service."
	} as ErrorText,
	si: {
		"msg404": "",
		"decription404": "",
		"msgUnknown": "",
		"decriptionUnknown": ""
	} as ErrorText,
	it: {
		"msg404": "",
		"decription404": "",
		"msgUnknown": "",
		"decriptionUnknown": ""
	} as ErrorText,
	ja: {
		"msg404": "",
		"decription404": "",
		"msgUnknown": "",
		"decriptionUnknown": ""
	} as ErrorText,
	zh: {
		"msg404": "",
		"decription404": "",
		"msgUnknown": "",
		"decriptionUnknown": ""
	} as ErrorText,
	ta: {
		"msg404": "",
		"decription404": "",
		"msgUnknown": "",
		"decriptionUnknown": ""
	} as ErrorText,
}

export default function (): ErrorText {
    return TextData[lang];
}