import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface FooterText {
	logoSubtitle: string
	subscribeToNewsletter: string
	subscribePlaceholder: string
	subscribe: string
	home: string
	aboutUs: string
	ourTeam: string
	contactUs: string
	resources: string
	newsFeed: string
	bitzchool: string
	reachUs: string
}

let TextData = {
	en: {
		"logoSubtitle": "Bitzquad - Solutions beyond technology",
		"subscribeToNewsletter": "Subscribe to Newsletter",
		"subscribePlaceholder": "Enter Your Email...",
		"subscribe": "Subscribe",
		"home": "Home",
		"aboutUs": "About Us",
		"ourTeam": "Our Team",
		"contactUs": "Contact Us",
		"resources": "Resources",
		"newsFeed": "News Feed",
		"bitzchool": "BitZchool",
		"reachUs": "Reach Us"
	} as FooterText,
	si: {
		"logoSubtitle": "",
		"subscribeToNewsletter": "අපගේ නවතම පුවත් දැන ගැනීම සඳහා ලියාපදිංචි වන්න",
		"subscribePlaceholder": "ඔබගේ විද්‍යුත් තැපෑල ලිපිනය ඇතුලත් කරන්න...",
		"subscribe": "ලියාපදිංචි වන්න",
		"home": "ප්‍රධාන පිටුව",
		"aboutUs": "අපි ගැන",
		"ourTeam": "අපගේ කණ්ඩායම",
		"contactUs": "අපිව සම්බන්ධ කරගන්න / අප අමතන්න",
		"resources": "සම්පත්",
		"newsFeed": "පුවත් ගොනුව / පුවත්",
		"bitzchool": "BitZchool",
		"reachUs": "අප වෙත ළඟා වන්න"
	} as FooterText,
	it: {
		"logoSubtitle": "",
		"subscribeToNewsletter": "Iscriviti alla Newsletter",
		"subscribePlaceholder": "Inserisci la tua Email",
		"subscribe": "Iscriviti",
		"home": "Home",
		"aboutUs": "Su di noi",
		"ourTeam": "Il Nostro Team",
		"contactUs": "Contattaci",
		"resources": "Ricerche",
		"newsFeed": "",
		"bitzchool": "BitZchool",
		"reachUs": "Come Trovarci"
	} as FooterText,
	ja: {
		"logoSubtitle": "",
		"subscribeToNewsletter": "",
		"subscribePlaceholder": "",
		"subscribe": "",
		"home": "",
		"aboutUs": "",
		"ourTeam": "",
		"contactUs": "",
		"resources": "",
		"newsFeed": "",
		"bitzchool": "",
		"reachUs": ""
	} as FooterText,
	zh: {
		"logoSubtitle": "",
		"subscribeToNewsletter": "",
		"subscribePlaceholder": "",
		"subscribe": "",
		"home": "",
		"aboutUs": "",
		"ourTeam": "",
		"contactUs": "",
		"resources": "",
		"newsFeed": "",
		"bitzchool": "",
		"reachUs": ""
	} as FooterText,
	ta: {
		"logoSubtitle": "",
		"subscribeToNewsletter": "",
		"subscribePlaceholder": "",
		"subscribe": "",
		"home": "",
		"aboutUs": "",
		"ourTeam": "",
		"contactUs": "",
		"resources": "",
		"newsFeed": "",
		"bitzchool": "",
		"reachUs": ""
	} as FooterText,
}

export default function (): FooterText {
    return TextData[lang];
}