import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface FooterText {
	logoSubtitle: string
	subscribeToNewsletter: string
	subscribePlaceholder: string
	subscribe: string
	home: string
	aboutUs: string
	ourTeam: string
	contactUs: string
	resources: string
	newsFeed: string
	bitzchool: string
	reachUs: string
}

let TextData = {
	en: {
		"logoSubtitle": "Bitzquad - Solutions beyond technology",
		"subscribeToNewsletter": "Subscribe to Newsletter",
		"subscribePlaceholder": "Enter Your Email...",
		"subscribe": "Subscribe",
		"home": "Home",
		"aboutUs": "About Us",
		"ourTeam": "Our Team",
		"contactUs": "Contact Us",
		"resources": "Resources",
		"newsFeed": "News Feed",
		"bitzchool": "BitZchool",
		"reachUs": "Reach Us"
	} as FooterText,
}

export default function (): FooterText {
    return TextData[lang];
}