import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface NavbarText {
	services: string
	contact: string
	blog: string
	about: string
}

let TextData = {
	en: {
		"services": "Services",
		"contact": "Contact",
		"blog": "News",
		"about": "About"
	} as NavbarText,
}

export default function (): NavbarText {
    return TextData[lang];
}