import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface ServiceSystemText {
	mainTitle: string
	mainDescription: string
	featureTitle1: string
	featureDescription1: string
	featureTitle2: string
	featureDescription2: string
	featureTitle3: string
	featureDescription3: string
}

let TextData = {
	en: {
		"mainTitle": "Information Systems",
		"mainDescription": "Upgrade with the best technology that helps your business grow",
		"featureTitle1": "Down to earth solutions",
		"featureDescription1": "We will visit your business, observe how it works, and speak with your employees and customers to deliver the best hand-tailored software that truly serves you.",
		"featureTitle2": "Flexible & User-friendly systems",
		"featureDescription2": "Our modular, serverless architecture will seamlessly scale up and down as your business grows. Adding or changing features will be just a phone call away.",
		"featureTitle3": "Military grade security",
		"featureDescription3": "Your system will be unbreachable and fail-safe with innovative security measures in this ever-changing industry. Your data, business strategies, and ideas will be safe and private."
	} as ServiceSystemText,
}

export default function (): ServiceSystemText {
    return TextData[lang];
}