import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface ServicesSectionText {
	title: string
	sysTitle: string
	sysDescription: string
	appTitle: string
	appDescription: string
	blockchainTitle: string
	blockchainDescription: string
	brandTitle: string
	brandDescription: string
	marketingTitle: string
	marketingDescription: string
	ecommerceTitle: string
	ecommerceDescription: string
}

let TextData = {
	en: {
		"title": "Our Services",
		"sysTitle": "Information Systems",
		"sysDescription": "Upgrade with the best technology that helps your business grow",
		"appTitle": "Software Development",
		"appDescription": "Powerful, yet intuitive web, desktop, and mobile apps",
		"blockchainTitle": "Blockchain Solutions",
		"blockchainDescription": "Prepare for the next technological revolution of decentralizing",
		"brandTitle": "Brand Design",
		"brandDescription": "Build a solid brand that one day, everyone will know",
		"marketingTitle": "Digital Marketing",
		"marketingDescription": "Let us bring your presence to your future customers",
		"ecommerceTitle": "E-commerce",
		"ecommerceDescription": "We develop e-commerce applications using the latest technologies"
	} as ServicesSectionText,
}

export default function (): ServicesSectionText {
    return TextData[lang];
}