import { lang } from "$lib/siteUtils";

// Do not edit this file manually, it is an auto-generated file.
// If you want to edit this file, please edit the source file in Google Sheets
// and run 'npm run text' command.

export interface ServiceBlockchainText {
	featureTitle: string
	featureDescription: string
}

let TextData = {
	en: {
		"featureTitle": "Block Chain Development",
		"featureDescription": "Blockchain enables you to create future-proof, distributed systems with maximum trust, transparency, and security. We specialize in building, maintaining, and securing decentralized apps (D-Apps) for financial, gaming, and other industries."
	} as ServiceBlockchainText,
}

export default function (): ServiceBlockchainText {
    return TextData[lang];
}